version: "3.9"
services:
  client:
    image: capstone/client
    ports:
      - "3000:3000"
    build: ./client

  auth:
    image: capstone/auth
    build: ./auth
    ports:
      - "3001:3001"
    environment:
      JWT_SECRET: "testsecret"
      MONGO_URI: "mongodb://auth-db:27017/auth"
    depends_on:
      - auth-db

  auth-db:
    image: mongo
    volumes:
      - ./auth-db:/data/db
    ports:
      - "4001:27017"

  cart:
    image: capstone/cart
    build: ./cart
    ports:
      - "3002:3002"
    environment:
      JWT_SECRET: "testsecret"
      MONGO_URI: "mongodb://cart-db:27017/cart"
    depends_on:
      - cart-db

  cart-db:
    image: mongo
    volumes:
      - ./cart-db:/data/db
    ports:
      - "4002:27017"

  product:
    image: capstone/product
    build: ./product
    ports:
      - "3003:3003"
    environment:
      JWT_SECRET: "testsecret"
      MONGO_URI: "mongodb://product-db:27017/product"
    volumes:
      - ./product/src/uploads:/app/src/uploads/
    depends_on:
      - product-db

  product-db:
    image: mongo
    volumes:
      - ./product-db:/data/db
    ports:
      - "4003:27017"

  order:
    image: capstone/order
    build: ./orders
    ports:
      - "3004:3004"
    environment:
      JWT_SECRET: "testsecret"
      MONGO_URI: "mongodb://order-db:27017/order"
    depends_on:
      - order-db

  order-db:
    image: mongo
    volumes:
      - ./order-db:/data/db
    ports:
      - "4004:27017"

  api-gateway:
    image: capstone/api-gateway
    build: ./api-gateway
    ports:
      - "4000:4000"
    environment:
      AUTH: "http://auth:3001"
      CART: "http://cart:3002"
      PRODUCT: "http://product:3003"
      ORDER: "http://order:3004"
      JWT_SECRET: "testsecret"
    depends_on:
      - auth
      - cart
      - product
      - product-db
      - cart-db
      - auth-db
